SUPABASE_URL = "https://enunchtqrychbbwumxiv.supabase.co"
SUPABASE_KEY = "sb_publishable_rsfCfT7OL9joo_HWB71v5Q_OSlUpg9I"
APP_PASSWORD = "MOS2026"
TEAM_MEMBERS = ["Matt Way", "Jon Freihaut", "Olly Howell", "Loz Hemmings", "Chris Neale", "Isabelle Blomfield", "James Rossiter", "Pat Moore"]